apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: entities
  description: a collection of all the catalog entities
spec:
  type: url
  targets:
    - https://github.com/PatAKnight/backstage-components/blob/main/catalog-entities/janus-idp/components/dotnetcore.yaml
    - https://github.com/PatAKnight/backstage-components/blob/main/catalog-entities/janus-idp/components/guestbook.yaml
    - https://github.com/PatAKnight/backstage-components/blob/main/catalog-entities/janus-idp/components/guestbook.yaml
    - https://github.com/PatAKnight/backstage-components/blob/main/catalog-entities/janus-idp/components/janus-idp-website.yaml
